server:
  port: 52328

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能
          lower-case-service-id: true
          filters:
            - StripPrefix=1
#      routes:
#        - id: library-book
#          uri: lb://library-book
#          predicates:
#            - Path=/library-book/**
#          filters:
#            - StripPrefix=1
logging:
  level:
    com.yulin.library.*: debug
    org.springframework.cloud.gateway.*: debug
    root: info