# 服务配置
server:
  port: 9001
# spring配置
spring:
  # 应用配置
  application:
    name: hrm-company
  # 数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.35.80:3306/saas_hrm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: developer@wlw
  # JPA
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true