management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  server:
    servlet:
      context-path: /actuator
  endpoints:
    web:
      exposure:
        include: refresh,health,info
spring:
  application:
    name: module-authority
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.22.1.21:3306/authority?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Developer@2019
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    borrowConnectionTimeout: 30000
    maxActive: 20
    maxWait: 10000
    minEvictableIdleTimeMillis: 300000
    minIdle: 3
    password: developer@2019
    timeBetweenEvictionRunsMillis: 60000
    url: jdbc:mysql://192.168.10.24:3306/tourism_quartz?useSSL=true
    username: root
    validationQuery: SELECT 'x' # 解决mysql8小时问题
  redis:
    database: 1
    host: 172.22.1.21
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: wlw@redis
    port: 6379
    timeout: 500000000ms

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ASSIGN_UUID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: ignored
      #驼峰下划线转换
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
    super-mapper-class: com.baomidou.mybatisplus.core.mapper.BaseMapper
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  check-config-location: true
  type-aliases-package: com.job.server.
