SERVER: 192.168.1.254
#SERVER: 127.0.0.1
MYSQL_PASSWORD: root
REDIS_PASSWORD: redis
server:
  port: 8771
spring:
  datasource:
    url: jdbc:mysql://${SERVER}:3306/system_set?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${SERVER}
    password: ${REDIS_PASSWORD}
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8766/.well-known/jwks.json

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.yulin.library.*: debug
    root: info
